In [10]:
import torch

# 학습 데이터 생성
x_train = torch.FloatTensor([ [1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7] ])
y_train = torch.FloatTensor([ [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0] ])

# W, b 초기화
# Optimizer 생성
W = torch.zeros(4, 3, requires_grad = True)
b = torch.zeros(1, 3, requires_grad = True)

optimizer = torch.optim.Adam([W, b], lr = 0.1)

# 반복 횟수 설정, 가설 및 비용 설정
for epoch in range(3001):
  hypothesis = torch.softmax(torch.mm(x_train, W) + b, dim = 1)
  cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim = 1))

  # hypothesis = (torch.mm(x_train, W) + b).softmax(dim = 1)
  # cost = -(y_train * torch.log(hypothesis)).sum(dim = 1).mean()

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))



epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105262
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [11]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]])
test_all = torch.softmax(torch.mm(x_test, W) + b, dim = 1)
print(test_all)
print(torch.argmax(test_all, dim = 1))

tensor([[1.0000e+00, 5.5165e-19, 7.0151e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


In [12]:
import torch.nn.functional as F

# 학습 데이터 생성
x_train = torch.FloatTensor([ [1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7] ])
y_train = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])

# W, b 초기화
# Optimizer 생성
W = torch.zeros(4, 3, requires_grad = True)
b = torch.zeros(1, 3, requires_grad = True)

optimizer = torch.optim.Adam([W, b], lr = 0.1)

# 반복 횟수 설정, 가설 및 비용 설정
for epoch in range(3001):
  z = torch.mm(x_train, W) + b
  cost = F.cross_entropy(z, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))



epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105263
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [13]:
import torch.nn as nn

# 학습 데이터 생성
x_train = torch.FloatTensor([ [1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7] ])
y_train = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])

model = nn.Linear(4, 3)
optimizer = torch.optim.Adam(model.parameters(), lr = 1)

# 반복 횟수 설정, 가설 및 비용 설정
for epoch in range(3001):
  z = model(x_train)
  cost = F.cross_entropy(z, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 4.672721
epoch: 300, cost: 0.028212
epoch: 600, cost: 0.010680
epoch: 900, cost: 0.005689
epoch: 1200, cost: 0.003547
epoch: 1500, cost: 0.002418
epoch: 1800, cost: 0.001744
epoch: 2100, cost: 0.001308
epoch: 2400, cost: 0.001009
epoch: 2700, cost: 0.000794
epoch: 3000, cost: 0.000636


In [14]:
import numpy as np
from sklearn.linear_model import LogisticRegression

x_train = torch.FloatTensor([ [1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7] ])
y_train = np.array([2, 2, 2, 1, 1, 1, 0, 0])

logistic = LogisticRegression()
logistic.fit(x_train, y_train)

pred = logistic.predict([[1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]])
print(pred)

[0 2 2]
